### ISSUE TITLE
Mindcraft BedRock Issue

### ISSUE THREAD

**Issue by nsaneadmin** [jesinmat/linux-gameservers#14]
Hi, When trying to install the mcb gameserver I was met this this error -
**"However the following packages replace it: lib32gcc-s1 E: Package 'lib32gcc1' has no installation candidate"**
I was able to fix the issue by updating the mcb config pre_install.sh  to "apt install -y lib32gcc-s1 lib32stdc++6"

**Comment by jesinmat** [comment]
Should be fixed by #15
