### ISSUE TITLE
Add Counter-Strike 2

### ISSUE THREAD

**Issue by uniquepurpose** [jesinmat/linux-gameservers#17]
Hi,
please add Counter-Strike 2 (AppID 730).
https://linuxgsm.com/servers/cs2server/

Thanks!

**Comment by jesinmat** [comment]
Done. Keep in mind that CS2 is a large game and downloading the server will take a long time.
Sometimes when I was testing this, running the install command failed at first, but running it again worked just fine, I'll have to look into that in the future.
